name: GameMode
version: 1.0
main: nl.wifivibes.gamemodepl.Main
description: Een GameMode plugin!

commands:
  gamemode:
    description: Verandert je gamemode
    aliases: [gm]
  fly:
    description: Zet je in vliegmodus!
